ci/kokoro/docker/check-api-presubmit.cfg, ci/kokoro/docker/check-api.cfg, ci/kokoro/docker/common.cfg, ci/kokoro/install/common.cfg, ci/kokoro/macos/continuous.cfg, ci/kokoro/macos/presubmit.cfg, ci/kokoro/readme/common.cfg, ci/kokoro/windows/bazel/common.cfg, ci/kokoro/windows/continuous-win-2019.cfg, ci/kokoro/windows/presubmit-win-2019.cfg, ci/test-install/CMakeLists.txt
Fix the CI configuration to use the right path for the build scripts.
Fix formatting to get build to pass.
=> bug: fix build script path.

super/ExternalProjectHelper.cmake, super/external/c-ares.cmake, super/external/crc32c.cmake, super/external/curl.cmake, super/external/googleapis.cmake, super/external/googletest.cmake, super/external/grpc.cmake, super/external/protobuf.cmake, super/external/zlib.cmake
If this looks familiar it is because we made the same changes in google-cloud-cpp.
=> cleanup: simplify external projects

README.md, ci/generate-badges.sh
Add Windows and some miscellaneous builds.
=> chore: update build badges

INSTALL.md, README.md, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/readme/Dockerfile.debian-buster, ci/test-readme/generate-install.sh, ci/test-readme/generate-readme.sh
This was released a few months ago, we should have a build for it.
Fixes #19
=> feat: enable builds for Debian 10 (Buster)

google/cloud/grpc_utils/CMakeLists.txt, google/cloud/grpc_utils/completion_queue_test.cc, google/cloud/grpc_utils/google_cloud_cpp_grpc_utils_unit_tests.bzl
Fixes #15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/32)
=> feat: implement smoke tests for CompletionQueue.

doc/cutting-a-release.md, google/cloud/README.md
The documentation on how to create a release for this repo needed a review too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/37)
=> doc: prepare release notes (and docs) for 0.13.0 release.

.bazelci/presubmit.yml
This will help us integrate with the Bazel CI system, so changes to
Bazel that might break our builds are detected as soon as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/40)
=> feat: configure basic Bazel CI build

bazel/google_cloud_cpp_common_deps.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/41)
=> doc: fix typo in a comment

ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/readme/Dockerfile.centos-7
A future PR will remove the old names, but we need to also change the
matching configurations inside Google. So first this PR, then the
internal change, then a second PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/51)
=> ci: copy centos configs to centos-7

ci/etc/repo-config.sh, ci/generate-badges.sh
Part of the work for #55 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/54)
=> ci: use a configuration file for generate-badges.sh

ci/kokoro/readme/build.sh
This fixes a reference to the wrong repository, and cleans up a variable
name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/61)
=> ci: cleanup names in build script

doc/cutting-a-release.md, google/cloud/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/67)
=> doc: prepare release notes for 0.14.0 release

google/cloud/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/77)
=> doc: prepare release notes for 0.15.0 release

doc/cutting-a-release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/79)
=> docs: update the release document

ci/etc/kokoro/install/project-config.sh, ci/etc/kokoro/install/run-installed-programs.sh
These are the configuration files to generate ci/kokoro/install.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/73)
=> ci: configuration files for ci/kokoro/install

ci/etc/kokoro/install/project-config.sh, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-trusty, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/install/build.sh, ci/templates/generate-kokoro-install.sh
Use the generator in ci/templates for ci/kokoro/install.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/81)
=> ci: automatically generate ci/kokoro/install

.github/issue_template.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/87)
=> chore: update issue template for the common repo

doc/cutting-a-release.md, google/cloud/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/89)
=> doc: prepare release notes for 0.16.0 release

README.md
This is a generated file, I just ran the generator again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/97)
=> doc: fix README.md instructions

google/cloud/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/117)
=> chore: release notes for v0.17.x

doc/setup-development-environment.md
Just went through these steps to setup a VM for myself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/119)
=> doc: update howto setup a Windows VM

bazel/google_cloud_cpp_common_deps.bzl, super/external/grpc.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/120)
=> chore: upgrade grpc to v1.26.0

release/release.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/124)
=> fix: fix clang-tidy breakage

google/cloud/grpc_utils/BUILD, google/cloud/grpc_utils/CMakeLists.txt, google/cloud/grpc_utils/completion_queue_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/142)
=> test: implement unit tests for async RPCs

INSTALL.md, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/templates/kokoro/install/Dockerfile.opensuse-tumbleweed.in
This build does not have a PR check (because it failed too often), so we
missed it in a previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/162)
=> ci: fix ci/kokoro/install/opensuse-tumbleweed

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/182)
=> chore: added v0.20.x release notes

google/cloud/connection_options_test.cc, google/cloud/log_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/184)
=> chore: migrate to `testing_util::ScopedEnvironment`

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/186)
=> chore: update release notes

ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/install/build.sh, ci/kokoro/readme/Dockerfile.centos-7, ci/kokoro/readme/Dockerfile.centos-8, ci/kokoro/readme/Dockerfile.debian-buster, ci/kokoro/readme/Dockerfile.debian-stretch, ci/kokoro/readme/Dockerfile.fedora, ci/kokoro/readme/Dockerfile.opensuse-leap, ci/kokoro/readme/Dockerfile.opensuse-tumbleweed, ci/kokoro/readme/Dockerfile.ubuntu-bionic, ci/kokoro/readme/Dockerfile.ubuntu-xenial, ci/kokoro/readme/build.sh, ci/kokoro/readme/common.cfg, ci/templates/kokoro/docker-fragments.sh, super/external/googleapis.cmake
Also update our own version in the ci/templates so we can generate other
project's Kokoro configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/188)
=> chore: update googleapis version for CMake

INSTALL.md, README.md, ci/kokoro/docker/Dockerfile.ubuntu, ci/kokoro/docker/Dockerfile.ubuntu-install, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/readme/Dockerfile.debian-buster, ci/kokoro/readme/Dockerfile.debian-stretch, ci/kokoro/readme/Dockerfile.ubuntu-bionic, ci/kokoro/readme/Dockerfile.ubuntu-xenial, ci/templates/kokoro/install/Dockerfile.debian-buster.in, ci/templates/kokoro/install/Dockerfile.debian-stretch.in, ci/templates/kokoro/install/Dockerfile.ubuntu-bionic.in, ci/templates/kokoro/install/Dockerfile.ubuntu-xenial.in, ci/templates/kokoro/readme/Dockerfile.debian-buster.in, ci/templates/kokoro/readme/Dockerfile.debian-stretch.in, ci/templates/kokoro/readme/Dockerfile.ubuntu-bionic.in, ci/templates/kokoro/readme/Dockerfile.ubuntu-xenial.in
This ports similar changes from googleapis/google-cloud-cpp#3417. Thanks to @Rajpratik71 for providing the motivation and a template to follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/189)
=> ci: reduce Docker image size for Ubuntu+Debian images

ci/kokoro/docker/Dockerfile.ubuntu, ci/kokoro/docker/Dockerfile.ubuntu-install, doc/setup-development-environment.md
Part of the work for #194 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/191)
=> ci: update builds to use Python 3

ci/kokoro/docker/Dockerfile.fedora, ci/kokoro/docker/Dockerfile.fedora-install, ci/kokoro/docker/Dockerfile.ubuntu
Missed a few in the last PR, part of the work for #194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/201)
=> fix: more updates to Python 3

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/214)
=> chore: update release notes for new release

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/218)
=> doc: link to the local changes to the style guide

ci/templates/kokoro/docker-fragments.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/222)
=> chore: update template version for dependent projects

doc/cutting-a-patch.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/221)
=> doc: describe how to create a patch release

ci/kokoro/docker/build-in-docker-bazel.sh, ci/kokoro/docker/build-in-docker-cmake.sh, ci/kokoro/docker/build.sh
This is a change equivalent to:
https://github.com/googleapis/google-cloud-cpp-spanner/pull/1360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/230)
=> testing: add RUNS_PER_TEST environment variable

ci/kokoro/windows/build-bazel.ps1
Part of the work for googleapis/google-cloud-cpp-common#233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/234)
=> ci: retry bazel fetch in Windows builds

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/247)
=> doc: update release notes

CHANGELOG.md
Yet another release. Note that there is a pending PR to update the version numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/254)
=> chore: update release notes for v0.24.0

ci/kokoro/docker/build.sh
Part of the work for #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/257)
=> ci: create configs for gcc-9 and clang-9 builds

ci/templates/kokoro/docker-fragments.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/259)
=> ci: fix generated crc32c version

release/release.sh
This PR teaches the release.sh script how to deal with version numbers
that don't start with a leading 0. This is important since Spanner is
now 1.0.0. release.sh now accepts an optional "new_version" argument to
let the user specify the desired new version number on the command line
rather than computing it from previous tags. This is useful when we want
to jump to a non-sequential version number. For example, this would have
worked for the Spanner 1.0.0 release we did a few days ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/264)
=> feat: release script accepts new_version arg

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/273)
=> chore: update release notes for v0.25.0

INSTALL.md, bazel/google_cloud_cpp_common_deps.bzl, ci/kokoro/docker/Dockerfile.fedora-install, ci/kokoro/docker/Dockerfile.ubuntu-install, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.fedora, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/templates/kokoro/docker-fragments.sh, super/external/googleapis.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/278)
=> chore: updated to cpp-cmakefiles 0.8.0

INSTALL.md, ci/etc/kokoro/install/project-config.sh, ci/kokoro/docker/Dockerfile.fedora-install, ci/kokoro/docker/Dockerfile.ubuntu-install, ci/kokoro/install/Dockerfile.centos-7, ci/kokoro/install/Dockerfile.centos-8, ci/kokoro/install/Dockerfile.debian-buster, ci/kokoro/install/Dockerfile.debian-stretch, ci/kokoro/install/Dockerfile.opensuse-leap, ci/kokoro/install/Dockerfile.opensuse-tumbleweed, ci/kokoro/install/Dockerfile.ubuntu-bionic, ci/kokoro/install/Dockerfile.ubuntu-focal, ci/kokoro/install/Dockerfile.ubuntu-xenial, ci/kokoro/install/build.sh, ci/templates/kokoro/docker-fragments.sh, super/external/googleapis.cmake
Automatically generated a number of files as part of this update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/282)
=> chore: update googleapis to v0.9.0

google/cloud/README.md, google/cloud/internal/README.md, google/cloud/testing_util/README.md
Fixes #3908
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/285)
=> doc: add README.md files to google/cloud/

ci/templates/generate-kokoro-install.sh, ci/templates/generate-kokoro-readme.sh, ci/templates/kokoro/docker-fragments-functions.sh
Part of the work for googleapis/google-cloud-cpp#3582
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/286)
=> cleanup: reformat scripts with shfmt
