- ci/kokoro/docker/define-docker-variables.sh
- ci/kokoro/install/build.sh
- ci/kokoro/readme/build.sh
Use more consistent naming for the docker images across the different
build types (install vs. readme vs. docker). Also use a folder (as
opposed to a name prefix) to separate the docker images for
google-cloud-cpp vs. google-cloud-cpp-common.
> cleanup: build scripts inconsistencies.

- ci/kokoro/docker/define-docker-variables.sh
I did not test using the build scripts interactively. Of course the fake
project name did not work.
> bug: fix interactive builds.

- doc/setup-cmake-environment.md
- super/CMakeLists.txt
Make it easier to cut&paste the instructions, and use a common name for the dependencies that will work across repositories.
> cleanup: simplify super build instructions.

- ci/kokoro/windows/build-bazel.ps1
- ci/kokoro/windows/build-cmake-dependencies.ps1
- ci/kokoro/windows/build-cmake.ps1
- ci/kokoro/windows/build.bat
- ci/kokoro/windows/build.ps1
- ci/kokoro/windows/cmake-presubmit.cfg
- ci/kokoro/windows/cmake.cfg
Fixed several bugs in the download of the vcpkg cache. Also setting
the `TEMP` environment variable to non-whitelisted values disables
functionality in PowerShell used by vcpkg. We need to keep the
default value until just before running the unit tests, at which
point the default does not work, sigh.
For the Bazel build we needed to set `BAZEL_VC` to the right location,
Bazel does not seem able to automatically detect MSVC 2019.
> bug: troubleshoot Windows builds

- INSTALL.md
- bazel/google_cloud_cpp_common_deps.bzl
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- super/external/googletest.cmake
Easier to point customers to what version we use if we use a named
release.
Fixes #14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/35)
> chore: upgrade googletest to the 1.10.0 release.

- INSTALL.md
- README.md
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/readme/Dockerfile.centos-8
- ci/test-readme/generate-install.sh
- ci/test-readme/generate-readme.sh
CentOS was released a couple of months ago, and it is one of the
supported distributions in GCE, we should test that the code works
there. Maybe it can help us remove the builds for CentOS:7 someday.
Fixes #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/36)
> feat: enable builds for CentOS 8

- doc/cutting-a-release.md
* Replaced occurrences of `google-cloud-cpp` with `google-cloud-cpp-common`.
* Added a TODO to update the version number push.
* Made the TODO about creating a doc push job visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/42)
> doc: linkify googleapis.dev and misc updates

- bazel/google_cloud_cpp_common_deps.bzl
We really do not need libcurl or crc32c in this project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/44)
> cleanup: reduce the Bazel dependencies

- .gitignore
The additional `/` for the bazel links was not working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/46)
> chore: fix the gitignore file

- .bazelignore
For folks that like to type `bazel build ...` we need to instruct Bazel
to ignore the build directories. These may contain test BUILD files that
are only usable in a Docker image or otherwise not usable from the
top-level directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/48)
> cleanup: tell Bazel to ignore build directories

- ci/install-bazel.sh
Now that Bazel reached 1.0 and it is expected to follow semver, it seems
better to test with that version. The downside is that we may not notice
breakage for users in the 0.24.0-0.29.0 range. But it seems that Bazel
users are rapidly moving towards using 1.0 anyway.
> ci: upgrade builds to use Bazel 1.0

- ci/kokoro/docker/build-in-docker-cmake.sh
The variable name to turn off is `GOOGLE_CLOUD_CPP_*ENABLE*_CCACHE`,
sigh. Also documented the variables a bit better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/49)
> ci: disable ccache for realsies

- ci/kokoro/readme/common.cfg
The builds were actually duplicating the work in the install builds and
not checking the README instructions. Unfortunately the builds
"worked", but failed to detect the openSUSE:Tumbleweed problems.
Part of the work for #56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/60)
> ci: fix the kokoro readme builds configuration

- ci/kokoro/readme/Dockerfile.centos-7
- ci/kokoro/readme/Dockerfile.centos-8
- ci/kokoro/readme/Dockerfile.debian-buster
- ci/kokoro/readme/Dockerfile.fedora
- ci/kokoro/readme/Dockerfile.opensuse-leap
- ci/kokoro/readme/Dockerfile.opensuse-tumbleweed
- ci/kokoro/readme/Dockerfile.ubuntu-xenial
- ci/templates/README.md
- ci/templates/generate-kokoro-readme.sh
- ci/templates/kokoro/readme/Dockerfile.centos-7.in
- ci/templates/kokoro/readme/Dockerfile.centos-8.in
- ci/templates/kokoro/readme/Dockerfile.debian-buster.in
- ci/templates/kokoro/readme/Dockerfile.debian-stretch.in
- ci/templates/kokoro/readme/Dockerfile.fedora.in
- ci/templates/kokoro/readme/Dockerfile.opensuse-leap.in
- ci/templates/kokoro/readme/Dockerfile.opensuse-tumbleweed.in
- ci/templates/kokoro/readme/Dockerfile.ubuntu-bionic.in
- ci/templates/kokoro/readme/Dockerfile.ubuntu-trusty.in
- ci/templates/kokoro/readme/Dockerfile.ubuntu-xenial.in
- ci/templates/kokoro/readme/build.sh
- ci/templates/kokoro/readme/common.cfg.in
In this change we introduce a shell script to generate
`ci/kokoro/readme`. The idea is to use the same script to generate that
directory for other projects (such as `google-cloud-cpp-spanner`, or
`g-c-cpp-bigquery`).
This fixes #56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/62)
> ci: automatically generate ci/kokoro/readme

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/internal/tuple.h
- google/cloud/internal/tuple_test.cc
- google/cloud/internal/utility.h
- google/cloud/internal/utility_test.cc
This is a part of googleapis/google-cloud-cpp#3016.
Composing GCS objects consists of multiple operations under the hood.
Different subsets of the options passed to the recursive compose
operation have to be passed on to the underlying operations.
By GCS C++ client convention, options are passed as parameter packs,
hence in the general case the filtering has to be done in compile time.
An easy way to filter these parameters is to pack them in a
`std::tuple`, process the tuple and apply it via `std::apply`.
Unfortunately, `std::apply` is only available in C++14, so this PR
reimplements it in a API-compatible way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-c …
> feat: implement std::apply

- ci/kokoro/define-docker-variables.sh
- ci/kokoro/docker/build.sh
- ci/kokoro/docker/dump-logs.sh
- ci/kokoro/docker/dump-reports.sh
- ci/kokoro/docker/publish-refdocs.sh
- ci/kokoro/docker/upload-coverage.sh
- ci/kokoro/docker/upload-docs.sh
- ci/kokoro/install/build.sh
- ci/kokoro/readme/build.sh
- ci/templates/kokoro/readme/build.sh
Move the define-docker-variables.sh file to a location where it can be
shared across the builds that use docker
(ci/kokoro/{docker,image,readme}) and define all the image names in this
file.
This new location is already in use by other repositories, and will make
it easier to share (or generate) build scripts for all repositories in
its new location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/68)
> ci: refactor definition of docker image names

- ci/templates/generate-kokoro-install.sh
- ci/templates/kokoro/install/Dockerfile.centos-7.in
- ci/templates/kokoro/install/Dockerfile.centos-8.in
- ci/templates/kokoro/install/Dockerfile.debian-buster.in
- ci/templates/kokoro/install/Dockerfile.debian-stretch.in
- ci/templates/kokoro/install/Dockerfile.fedora.in
- ci/templates/kokoro/install/Dockerfile.opensuse-leap.in
- ci/templates/kokoro/install/Dockerfile.opensuse-tumbleweed.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-bionic.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-trusty.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-xenial.in
- ci/templates/kokoro/install/build.sh
- ci/templates/kokoro/install/build.sh.in
- ci/templates/kokoro/install/docker-fragments-functions.sh
- ci/templates/kokoro/install/docker-fragments.sh
This PR introduces scripts and configuration files to automatically
generate `ci/kokoro/install`, but does not change the files in that
directory. The idea is to give folks a chance to evaluate the generators
by themselves before we decide this is the way to go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/72)
> ci: scripts to generate ci/kokoro/install

- google/cloud/internal/tuple.h
- google/cloud/internal/tuple_test.cc
`ApplyRes<>` used to try to match `std::tuple<>&` against `std::tuple<>`
and failed. This PR adds necessary `std::decay<>` to avoid it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/85)
> fix: std::apply doesn't work for std::tuple<>&

- INSTALL.md
- ci/etc/kokoro/install/project-config.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/templates/kokoro/install/Dockerfile.centos-7.in
- ci/templates/kokoro/install/Dockerfile.centos-8.in
- ci/templates/kokoro/install/Dockerfile.debian-stretch.in
- ci/templates/kokoro/install/Dockerfile.opensuse-leap.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-bionic.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-trusty.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-xenial.in
- ci/templates/kokoro/install/docker-fragments.sh
- ci/test-readme/dockerfile2markdown.sh
I started by porting the changes from google-cloud-cpp to fix the
CentOS-7 and openSUSE/Leap instructions. In the process I noted that
using /o as the output directory was good for a Docker image, but not
for the instructions we generate from them (as I think @mr-salty tried
to tell me), so I fixed that too. Then I regenerated INSTALL.md with the
missing `sudo` commands.
This fixes #82. Note that `INSTALL.md` and `ci/kokoro/install/*` are
generated files, you may want to skip them and just look at the sources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/84)
> docs: fix instructions for CentOS 7 (and others)

- ci/kokoro/docker/Dockerfile.ubuntu-install
- super/external/protobuf.cmake
I upgraded gRPC to 1.24.3, but missed a couple of places where we still
used protobuf-3.6.1. The newer gRPC requires the newer protobuf. This
was undetected by the builds because they fallback on the previously
cached docker image when creating the image fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/91)
> ci: update protobuf to-3.9.1

- INSTALL.md
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/templates/kokoro/docker-fragments.sh
Depending on how the server is configured the Docker images may have a
limit on the number of layers (about 120), and we are getting close to
this limit in some of our builds. Each `RUN` command creates a new
layer, so we can avoid creating too many by combining `RUN` and
`WORKDIR` commands using `&&`.
Note that `INSTALL.md` and  the files in `ci/kokoro/install` are automatically
generated.  Reviewing `ci/templates/*` may be less repetitive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/94)
> ci: reduce layers in ci/kokoro/install Docker images

- CMakeLists.txt
- ci/kokoro/docker/build-in-docker-cmake.sh
The `google-cloud-cpp-dependencies` target is a remant from the days
when we automatically downloaded and compiled dependencies as part of
the top-level CMake file. We no longer do this, and therefore no longer
need the target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/92)
> cleanup: remove *-dependencies target

- ci/etc/kokoro/install/project-config.sh
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-buster
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.fedora
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.opensuse-tumbleweed
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-trusty
- ci/kokoro/install/Dockerfile.ubuntu-xenial
Whenever a `FROM` directive appears in a Dockerfile, all `ARG`s need to
be redeclared. Otherwise, they won't be propagated to the environment of
the executed commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/96)
> fix: placement of ARGs in install Dockerfiles

- ci/kokoro/readme/Dockerfile.centos-7
- ci/kokoro/readme/Dockerfile.centos-8
- ci/kokoro/readme/Dockerfile.debian-buster
- ci/kokoro/readme/Dockerfile.debian-stretch
- ci/kokoro/readme/Dockerfile.fedora
- ci/kokoro/readme/Dockerfile.opensuse-leap
- ci/kokoro/readme/Dockerfile.opensuse-tumbleweed
- ci/kokoro/readme/Dockerfile.ubuntu-bionic
- ci/kokoro/readme/Dockerfile.ubuntu-trusty
- ci/kokoro/readme/Dockerfile.ubuntu-xenial
- ci/kokoro/readme/build.sh
- ci/kokoro/readme/common.cfg
- ci/templates/generate-kokoro-readme.sh
- ci/templates/kokoro/docker-fragments.sh
- ci/templates/kokoro/readme/Dockerfile.centos-7.in
- ci/templates/kokoro/readme/Dockerfile.centos-8.in
- ci/templates/kokoro/readme/Dockerfile.debian-buster.in
- ci/templates/kokoro/readme/Dockerfile.debian-stretch.in
- ci/templates/kokoro/readme/Dockerfile.fedora.in
- ci/templates/kokoro/readme/Dockerfile.opensuse-leap.in
- ci/templates/kokoro/readme/Dockerfile.opensuse-tumbleweed.in
- ci/templates/kokoro/readme/Dockerfile.ubuntu-bionic.in
- ci/templates/kokoro/readme/Dockerfile.ubuntu-trusty.in
- ci/templates/kokoro/readme/Dockerfile.ubuntu-xenial.in
These are some final tweaks:
* Add the "automatically generated warnings"
* Refactor the `FROM devtools AS readme` line
* Place `ARG NCPU=...` in the right places
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/95)
> ci: more fixes for ci/kokoro/readme

- ci/etc/kokoro/readme/project-config.sh
- ci/templates/generate-kokoro-readme.sh
To generate the ci/kokoro/readme files in `google-cloud-cpp` we need the
copyright year to be configurable. No changes in the generated files for
this repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/98)
> ci: configure copyright year for ci/kokoro/readme

- ci/templates/kokoro/docker-fragments.sh
The downstream dependencies of g-c-cpp-common should be using the latest
release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/99)
> ci: generate ci scripts using newer g-c-cpp-common

- INSTALL.md
- ci/kokoro/install/Dockerfile.debian-buster
- ci/templates/kokoro/install/Dockerfile.debian-buster.in
Only noticeable in g-c-cpp and g-c-cpp-spanner, but we need the
development version of libc-ares as we use this library indirectly (via
gRPC).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/105)
> ci: fix Debian-10 (Buster) install instructions

- ci/kokoro/install/build.sh
- ci/kokoro/readme/build.sh
- ci/templates/kokoro/install/build.sh.in
- ci/templates/kokoro/readme/build.sh.in
We need to source the Google Container Registry (GCR) configuration
before defining the docker image names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/106)
> ci: fix Docker image caching

- doc/cutting-a-release.md
- release/release.sh
Related to https://github.com/googleapis/google-cloud-cpp-spanner/issues/1187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/126)
> chore: remove sha256sum step from release process

- CHANGELOG.md
- doc/cutting-a-release.md
- release/release.sh
Part of https://github.com/googleapis/google-cloud-cpp/issues/3334
Note also in this case, the release notes used to be inside the `google/cloud` directory. In this PR, I'm putting the release notes in a top-level `CHANGELOG.md` file, and I'm removing the google/cloud/README.md file, which seems to be unnecessary since we split "common" from google-cloud-cpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/128)
> chore: move release notes to CHANGELOG.md

- google/cloud/grpc_utils/completion_queue.cc
- google/cloud/grpc_utils/completion_queue.h
- google/cloud/grpc_utils/completion_queue_test.cc
- google/cloud/grpc_utils/internal/completion_queue_impl.cc
- google/cloud/grpc_utils/internal/completion_queue_impl.h
The underlying `grpc::CompletionQueue` requires draining all events
before it is safe to delete a completion queue. Therefore we need to
drain the queue before returning from `CompletionQueue::Run()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/127)
> fix: crashes with non-empty CompletionQueue shutdown

- google/cloud/grpc_utils/internal/completion_queue_impl.cc
- google/cloud/grpc_utils/internal/completion_queue_impl.h
`shutdown_ && pending_ops_.empty()` will be true exactly when the next call to `AsyncNext()` will return `SHUTDOWN`, so we should just rely on the latter without checking the former.
(we could possibly `assert(shutdown_ && pending_ops_.empty())` at the end of the loop but it didn't seem worthwhile).
part of #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/131)
> fix: remove the redundant conditions in the `Run()` loop

- google/cloud/grpc_utils/completion_queue.cc
- google/cloud/grpc_utils/completion_queue.h
- google/cloud/grpc_utils/completion_queue_test.cc
The result of the `future` returned from `MakeDeadlineTimer` and
`MakeRelativeTimer` is now a `StatusOr` that indicates whether the
timer ran to expiration or not (e.g. it was Cancelled).
BREAKING CHANGE: Most callers of `MakeDeadlineTimer` or `MakeRelativeTimer` will need to be updated.
Part of #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/134)
> feat!: change the result type for timers to StatusOr

- google/cloud/grpc_utils/completion_queue.cc
- google/cloud/grpc_utils/completion_queue_test.cc
- google/cloud/grpc_utils/internal/async_read_stream_impl.h
- google/cloud/grpc_utils/internal/completion_queue_impl.cc
- google/cloud/grpc_utils/internal/completion_queue_impl.h
This parameter was unused, so remove it.
Also remove `CompletionQueue` from `Run()` and `SimulateCompletion()` which
only passed it through to `Notify()`.
Part of #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/136)
> chore: remove `CompletionQueue` parameter to `AsyncGrpcOperation::Notify`

- ci/templates/kokoro/docker-fragments.sh
Allow google-cloud-cpp projects to generate installation rules
that use `https://github.com/google/benchmark`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/140)
> feat: add support for INSTALL_GOOGLE_BENCHMARK_FROM_SOURCE

- google/cloud/grpc_utils/completion_queue_test.cc
No need to wait for X milliseconds on the future. We are going to block
on the same future later on the test, that is really what we want to
verify, that the function is called "eventually".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/143)
> fix: make test not flaky

- google/cloud/grpc_utils/completion_queue.cc
- google/cloud/grpc_utils/completion_queue.h
- google/cloud/grpc_utils/completion_queue_test.cc
- google/cloud/grpc_utils/internal/async_read_stream_impl.h
- google/cloud/grpc_utils/internal/completion_queue_impl.cc
- google/cloud/grpc_utils/internal/completion_queue_impl.h
The grpc `CompletionQueue` asserts if items are added to it after
`Shutdown()` is called. Make our `CompletionQueue` a little friendlier
by just failing those operations immediately.
Part of #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/138)
> feat: gracefully fail adding to the `CompletionQueue` after `Shutdown`

- bazel/google_cloud_cpp_common_deps.bzl
- super/external/grpc.cmake
Workaround grpc/grpc#21280 by compiling against a specific commit
(without a tag) of the v1.26.x gRPC branch.
This fixes #145 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/146)
> ci: use gRPC-1.26.x to workaround a known bug

- ci/templates/generate-kokoro-install.sh
- ci/templates/generate-kokoro-readme.sh
- ci/templates/kokoro/docker-fragments-functions.sh
- ci/test-readme/generate-readme.sh
SC1091: Disable if we don't statically know the source path.
SC2016: `shellcheck` thinks the `` `/\\` `` is a command substitution.
SC2086: Double quote ${BINDIR} expansion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/148)
> fix: avoid/quash some shellcheck warnings

- INSTALL.md
- README.md
- WORKSPACE
- bazel/google_cloud_cpp_common_deps.bzl
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/install/Dockerfile.centos-7
- ci/kokoro/install/Dockerfile.centos-8
- ci/kokoro/install/Dockerfile.debian-stretch
- ci/kokoro/install/Dockerfile.opensuse-leap
- ci/kokoro/install/Dockerfile.ubuntu-bionic
- ci/kokoro/install/Dockerfile.ubuntu-xenial
- ci/templates/kokoro/docker-fragments.sh
- ci/test-readme/generate-readme.sh
- super/external/protobuf.cmake
We need protobuf-3.11.3 to successfully compile the latest and greatest
protos on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/151)
> ci: use protobuf-3.11.3 in the builds and docs

- INSTALL.md
- ci/test-install/WORKSPACE
- ci/test-readme/generate-install.sh
This (new with gRPC-1.26.0) function loads the dependencies of gRPC.
This is easier to use than listing each dependency ourselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/152)
> ci: use grpc_extra_deps() for gRPC dependencies

- doc/cutting-a-release.md
Remove remnant text about removing a clone directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/159)
> docs: update doc/cutting-a-release.md

- google/cloud/future_generic.h
- google/cloud/future_generic_test.cc
- google/cloud/future_void.h
- google/cloud/future_void_test.cc
- google/cloud/internal/future_base.h
- google/cloud/internal/future_impl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/160)
> feat: support cancellation for long running operations

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_common.bzl
- google/cloud/google_cloud_cpp_common_unit_tests.bzl
- google/cloud/tracing_options.cc
- google/cloud/tracing_options.h
- google/cloud/tracing_options_test.cc
Copy the `TracingOptions` class from `google-cloud-cpp-spanner`. I need
them in `google-cloud-cpp-pubsub`, and it seems terrible to just copy
the code. The plan is to first copy the classes here (so we can start
using them in `g-c-cpp-pubsub`) and then create aliases in
`g-c-cpp-spanner` that point to the classes in this repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/161)
> refactor: copy TracingOptions from spanner

- google/cloud/CMakeLists.txt
- google/cloud/background_threads.h
- google/cloud/google_cloud_cpp_grpc_utils.bzl
- google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
- google/cloud/internal/background_threads_impl.cc
- google/cloud/internal/background_threads_impl.h
- google/cloud/internal/background_threads_impl_test.cc
Copy `BackgroundThreads` from `google::cloud::spanner`, planning to
later remove the class from that repository (`g-c-cpp-spanner`), leaving
an alias for backwards compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/163)
> refactor: copy BackgroundThreads from spanner

- google/cloud/completion_queue.cc
- google/cloud/completion_queue_test.cc
- google/cloud/future_generic_then_test.cc
- google/cloud/future_void_then_test.cc
- google/cloud/internal/future_impl.h
- google/cloud/internal/future_then_impl.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/166)
> feat: cancel futures returned by .then()

- google/cloud/internal/future_impl.h
Thanks to @devbww for the suggestion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/167)
> cleanup: use more idiomatic name for function

- google/cloud/CMakeLists.txt
- google/cloud/connection_options.cc
- google/cloud/connection_options.h
- google/cloud/connection_options_test.cc
- google/cloud/google_cloud_cpp_grpc_utils.bzl
- google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
- google/cloud/testing_util/environment_variable_restore.h
The plan is to copy the class here, and later remove it from spanner, we
need it for Cloud Pub/Sub too. This is not strictly a copy, the defaults
are different for each service, for example: the endpoint. The class is
a template, parametized by traits to set the defaults. Each client
library will instantiate this class with the right set of defaults.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/165)
> refactor: copy ConnectionOptions from spanner

- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_grpc_utils.bzl
- google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
- google/cloud/internal/pagination_range.h
- google/cloud/internal/pagination_range_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/168)
> refactor: copy PaginationRange from spanner

- ci/test-install/BUILD
- google/cloud/BUILD
- google/cloud/completion_queue_test.cc
- google/cloud/grpc_utils/BUILD
- google/cloud/samples/BUILD
Keep the //google/cloud/grpc_utils:google_cloud_cpp_grpc_utils target
around for backwards compatibility. The backwards compatibility headers
are only available if one uses this target. The new target (one
directory up) only gives you access to the new headers. No changes for
CMake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/170)
> fix: grpc_utils backwards compatibility for Bazel

- doc/cutting-a-release.md
Now that the release notes are in CHANGELOG.md, these steps are no longer necessary. So simplifying the release process
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/173)
> chore: removed unnecessary steps from release process

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/172)
> chore: added v0.19.x release notes

- ci/templates/kokoro/docker-fragments.sh
- doc/cutting-a-release.md
In the future, this should probably be during while cutting the release, so I updated the release instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/176)
> chore: update docker fragments to use new v0.19 version of common

- google/cloud/connection_options.cc
- google/cloud/connection_options.h
- google/cloud/connection_options_test.cc
- google/cloud/log.cc
- google/cloud/log.h
- google/cloud/log_test.cc
Users can now enable logging to `std::clog` without any code changes or
recompiling their code simply by setting the
"GOOGLE_CLOUD_CPP_ENABLE_CLOG" environment variable before running their
program.
This env var is currently being inspected and set in some of our other
code, such as
https://github.com/googleapis/google-cloud-cpp-spanner/blob/20e2f9b011e3747fe5a8b8dc284245c11ff354b6/google/cloud/spanner/connection_options.cc#L68,
and we should remove that after this change is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/181)
> feat: logging can be enabled via env var

- google/cloud/testing_util/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/185)
> fix: install google_cloud_cpp_testing_grpc headers

- .cmake-format.py
- super/CMakeLists.txt
Sometimes we want to use a super build for development (or users might
use a super build for exploration), without BUILD_ALWAYS the code is not
compiled after a change.
Also fixed formatting configuration for cmake-format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/192)
> fix: use BUILD_ALWAYS in super build

- .clang-tidy
- ci/kokoro/docker/Dockerfile.fedora-install
- ci/kokoro/docker/Dockerfile.ubuntu-install
- ci/kokoro/docker/build-in-docker-cmake.sh
- ci/kokoro/docker/build.sh
- google/cloud/future_generic.h
- google/cloud/future_generic_test.cc
- google/cloud/future_generic_then_test.cc
- google/cloud/future_void.h
- google/cloud/future_void_test.cc
- google/cloud/future_void_then_test.cc
- google/cloud/internal/build_info.cc.in
- google/cloud/internal/compiler_info.cc
- google/cloud/internal/completion_queue_impl.cc
- google/cloud/internal/filesystem_test.cc
- google/cloud/internal/format_time_point.cc
- google/cloud/internal/future_impl.h
- google/cloud/internal/future_impl_test.cc
- google/cloud/internal/future_then_meta.h
- google/cloud/internal/pagination_range_test.cc
- google/cloud/internal/parse_rfc3339.cc
- google/cloud/internal/utility.h
- google/cloud/log.cc
- google/cloud/log.h
- google/cloud/optional_test.cc
- google/cloud/testing_util/chrono_literals.h
- google/cloud/testing_util/expect_exception.h
- google/cloud/testing_util/expect_future_error.h
- google/cloud/testing_util/scoped_environment_test.cc
- release/release.sh
Use the clang-tidy distributed with Fedora (currently clang-tidy-9) in
this repository. I am planning to make similar changes in the other
repositories and bring all our `clang-tidy` builds to use the same
versions of `clang-format`, `clang-tidy`, `doxygen`, `buildifier`,
`shellcheck`, and `cmake_format`.
I also updated the clang-tidy configuration to match the newer repos
(`-pubsub` and `-spanner`), and cleaned up any errors found in the
files.
Finally, fixed a number of Doxygen comments that used `<U>` (for a
template parameter) which Doxygen thought was an unordered list or
something.
Part of the work for #204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp- …
> cleanup: use same clang-tidy in all repositories

- google/cloud/internal/random.cc
- google/cloud/internal/random.h
- google/cloud/internal/random_test.cc
On fairly recent versions of libstdc++ the `std::random_device` class
fails when used by multiple threads:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94087
We workaround this problem by detecting the version of the standard C++
library, and if it is `libstdc++` and it is a version after 20200128
then we use `rdrand` as the token value to initialize
`std::random_device`, which does not have the problem with multiple
threads.
Part of the work for googleapis/google-cloud-cpp#3437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/208)
> fix: workaround a libstdc++ on random_device

- release/release.sh
I broke this in a previous PR cleaning up shellcheck warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/216)
> fix: correct logic in release script

- doc/cpp-style-guide.md
All of our repos follow this convention so it belongs in common.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/217)
> doc: copy the `Include Guards` section from the -cpp repo

- google/cloud/internal/parse_rfc3339.cc
- google/cloud/internal/parse_rfc3339_test.cc
It was not accepting 59 as a valid minute, this bug was introduced in
the clang-tidy cleanup, and our tests validate that things *outside* the
valid ranges are correctly reported as errors, but not that things
*exactly* at the boundary conditions are reported as valid. Sigh.
I already marked the release as invalid, tomorrow we can decide how
to create a new release (patch or completely increment the numbers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/219)
> fix: correct range validation in ParseRfc3339

- ci/kokoro/windows/build.bat
Part of the work for googleapis/google-cloud-cpp-common#231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/232)
> ci: actually use Bazel 2.0 in the build

- google/cloud/BUILD
- google/cloud/CMakeLists.txt
- google/cloud/google_cloud_cpp_grpc_utils.bzl
- google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
- google/cloud/internal/async_retry_unary_rpc.h
- google/cloud/internal/async_retry_unary_rpc_test.cc
- google/cloud/internal/retry_policy.h
- google/cloud/testing_util/CMakeLists.txt
- google/cloud/testing_util/google_cloud_cpp_testing_grpc.bzl
- google/cloud/testing_util/mock_async_response_reader.h
- google/cloud/testing_util/mock_completion_queue.h
Part of the work for #243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/244)
> refactor: adapt async retry loop from Bigtable

- ci/kokoro/docker/Dockerfile.centos
- ci/kokoro/docker/Dockerfile.ubuntu
- ci/kokoro/docker/build.sh
- google/cloud/internal/parse_rfc3339.cc
- google/cloud/log.cc
Just more builds, these are important because some of the other projects
have them, and they break when a new release of `-common` cannot compile
with those compilers. We just had that happen with `-pubsub`. There are
some formatting changes triggered by the double braces, I chose not to
argue with clang-format (I never do).
Fixes #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/253)
> ci: configs for clang-3.8 and gcc-4.8 builds

- google/cloud/testing_util/mock_async_response_reader.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/265)
> fix: include needed header

- .clang-tidy
- google/cloud/log.cc
- google/cloud/log.h
- google/cloud/log_test.cc
Timestamps are always rendered in "Zulu" time, and with nanosecond
resolution (no matter what the actual resolution of a platform's
`system_clock::time_point`).
Also disable the "readability-magic-numbers" clang tidy.  It is too
conservative for our liking.
Fixes #261.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/266)
> feat: add timestamps in default log backend

- .clang-format
Part of https://github.com/googleapis/google-cloud-cpp/issues/3596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/267)
> fix: copy .clang-format from -spanner

- ci/kokoro/docker/build-in-docker-cmake.sh
This fixes #269 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/270)
> ci: preemptively create ccache config

- google/cloud/internal/random.cc
The workaround put in place in #208 does not work with g++-9.3.1 on
Fedora:31. Despite this being a "newer" version of libstdc++, it does
not support `rdrand` as a token for `std::random_device` maybe because
the CPU specific tokens are not enabled.
For now, use `/dev/urandom` which seems to be supported on all Linux
distros. On other platforms we continue to use the default constructor
for `std::random_device`.
It might be possible to refine this and detect, at run-time, if `rdrand`
is supported, but that seems like an improvement that can wait a little
bit.
Fixes #271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/272)
> fix: use a safer token to workaround libstdc++ bug

- cmake/FindProtobufWithTargets.cmake
@coryan Same trouble as with google-cloud-cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/275)
> fix(cmake): typo when looking for protobuf-config

- bazel/googleapis.BUILD
- google/cloud/BUILD
- google/cloud/grpc_utils/BUILD
- google/cloud/samples/BUILD
We want to minimize the custom targets that we add to overlay `build_file`s, because these are deps that our *customers* will also have to define in their overlay build files as well. So any targets we add should be few and important.
This PR removes all of our overlay targets except for a single one called "googleapis_system_includes", which lets us include googleapis protos using angle brackets. Yes, customers will still need to define this target, but it's a single target and a simple one. If one day we can get rid of this one too, even better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/279)
> fix: minimize targets in overlay build_file

- google/cloud/CMakeLists.txt
- google/cloud/testing_util/CMakeLists.txt
CMake requires target names to be unique, even in different directories.
Fortunately the target name can be different from the binary name,
though it requires a little more work to make it so. Unit tests are more
likely to repeat names, so use a prefix to minimize the possibility of
collisions. The other targets can be handled on a ad-hoc basis when and
if we have a target name collision.
Part of the work for googleapis/google-cloud-cpp#3548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/280)
> cleanup: make unit test target names unique

- ci/templates/generate-kokoro-install.sh
- ci/templates/kokoro/install/Dockerfile.ubuntu-focal.in
- ci/templates/kokoro/install/build.sh.in
Ubuntun:20.04 (Focal Fossa) recently became available, this PR creates a
template for it and fixes the `build.sh.in` template to be compatible
with shmft.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/281)
> ci: update templates for Ubuntu:Focal

- google/cloud/CMakeLists.txt
- google/cloud/testing_util/CMakeLists.txt
When we move the code to `g-c-pp` we do not want the copyright year to
change just because the implementation of the export functions may have
a different default.
Fixes #3907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/284)
> chore: pin copyright year for generated .bzl files

- cmake/FindgRPC.cmake
Newer versions of CMake warn about using
`find_package_handle_standard_args()` through an include (correctly so),
so use `find_package()` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/283)
> fix: avoid warnings in newer CMake versions

- ci/templates/generate-kokoro-install.sh
- ci/templates/kokoro/install/Dockerfile.centos-7.in
- ci/templates/kokoro/install/Dockerfile.centos-8.in
- ci/templates/kokoro/install/Dockerfile.debian-buster.in
- ci/templates/kokoro/install/Dockerfile.debian-stretch.in
- ci/templates/kokoro/install/Dockerfile.fedora.in
- ci/templates/kokoro/install/Dockerfile.opensuse-leap.in
- ci/templates/kokoro/install/Dockerfile.opensuse-tumbleweed.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-bionic.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-focal.in
- ci/templates/kokoro/install/Dockerfile.ubuntu-xenial.in
- ci/templates/kokoro/install/build.sh.in
The templates now generate scripts with support
for ccache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp-common/288)
> ci: support ccache in install builds
